version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend-Customer
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend-Customer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./Backend-Customer/backend.env
    #environment:
    #  MONGO_URI: mongodb://mongo:27017/customerDB
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - data:/data/db

volumes:
  data: