apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-customer
  labels:
    app: backend-customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-customer
  template:
    metadata:
      labels:
        app: backend-customer
    spec:
      containers:
      - name: backend-customer
        image: sin.ocir.io/idxkccw2srke/backend-customer:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DB
          value: "customerDB"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend-customer-svc
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.ap-singapore-1.aaaaaaaarv5xdkoxqhhvzbxqzqwn5kkik2pvxnyg3lvf6jb43zl5w6euvqea"
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: backend-customer