apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-customer
  labels:
    app: backend-customer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-customer
  template:
    metadata:
      labels:
        app: backend-customer
    spec:
      containers:
      - name: backend-customer
        image: your-docker-repo/backend-customer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        - name: MONGO_HOST
          value: mongodb
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DB
          value: customerDB
        imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend-customer-svc
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: backend-customer