apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-customer
  labels:
    app: frontend-customer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-customer
  template:
    metadata:
      labels:
        app: frontend-customer
    spec:
      containers:
      - name: frontend-customer
        image: sin.ocir.io/idxkccw2srke/frontend-customer:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-customer-svc
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.ap-singapore-1.aaaaaaaarv5xdkoxqhhvzbxqzqwn5kkik2pvxnyg3lvf6jb43zl5w6euvqea"
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: frontend-customer